import {
    Loader2,
    LucideIcon,
    Moon,
    SunMedium,
    Twitter,
    User,
    Wallet,
    X,
    Menu,
    Ticket,
    Calendar,
    MapPin,
    Search,
    Filter,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Plus,
    Image as ImageIcon,
    Check,
    AlertCircle,
    LogOut,
    Copy,
    ExternalLink,
    Share2,
    MessageSquare,
    Heart,
    QrCode,
    DollarSign,
    ArrowUpDown,
    Edit,
    BarChart3,
    Home,
    Download,
    Facebook,
    Linkedin,
    MessageCircle,
    Minus,
    Upload,
    Send,
    Twitter as TwitterIcon,
    Github
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
    spinner: Loader2,
    sun: SunMedium,
    moon: Moon,
    twitter: Twitter,
    user: User,
    wallet: Wallet,
    close: X,
    menu: Menu,
    ticket: Ticket,
    calendar: Calendar,
    location: MapPin,
    mapPin: MapPin,
    search: Search,
    filter: Filter,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    add: Plus,
    plus: Plus,
    image: ImageIcon,
    check: Check,
    warning: AlertCircle,
    alertCircle: AlertCircle,
    logout: LogOut,
    copy: Copy,
    external: ExternalLink,
    share: Share2,
    comment: MessageSquare,
    heart: Heart,
    qrcode: QrCode,
    dollarSign: DollarSign,
    arrowUpDown: ArrowUpDown,
    x: X,
    edit: Edit,
    barChart: BarChart3,
    home: Home,
    download: Download,
    facebook: Facebook,
    linkedin: Linkedin,
    messageCircle: MessageCircle,
    minus: Minus,
    upload: Upload,
    telegram: Send,
    twitterX: TwitterIcon,
    github: Github
}
