import {
    Loader2,
    LucideIcon,
    Moon,
    SunMedium,
    Twitter,
    User,
    Wallet,
    X,
    Menu,
    Ticket,
    Calendar,
    MapPin,
    Search,
    Filter,
    ChevronLeft,
    ChevronRight,
    Plus,
    Image as ImageIcon,
    Check,
    AlertCircle,
    LogOut,
    Copy,
    ExternalLink,
    Share2,
    MessageSquare,
    Heart,
    QrCode
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
    spinner: Loader2,
    sun: SunMedium,
    moon: Moon,
    twitter: Twitter,
    user: User,
    wallet: Wallet,
    close: X,
    menu: Menu,
    ticket: Ticket,
    calendar: Calendar,
    location: MapPin,
    search: Search,
    filter: Filter,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    add: Plus,
    image: ImageIcon,
    check: Check,
    warning: AlertCircle,
    logout: LogOut,
    copy: Copy,
    external: ExternalLink,
    share: Share2,
    comment: MessageSquare,
    heart: Heart,
    qrcode: QrCode
}
